services:
  proxy:
    image: vlakam/docker-telegram-bot-api-proxy:amd64
  container_name: proxy
  
  tgbotrun:
    image: tgbot
      environment:
        
      depends_on:
         
    container_name: tgbotrun